### ISSUE TITLE
Cannot close first bubble

### ISSUE THREAD

**Issue by nator333** [nator333/longman-chrome-extention#1]
From a reviewer on the Chrome store.

There is a big problem that if there are two pop-up windows, I can not close the first one after close the second one. Especially when I double click a word showed in the first pop-up window because I don't understand the explanation.
The first one pop-up window cannot be closed. The only way I can do was to press "F5" to refresh.

**Comment by keisen** [comment]
Hi, @nator333 , Thank you for your great work.

I'm facing the same problem.
Is there any update on this?

Best regards.

**Comment by nator333** [comment]
Thank you for the reminder! I'm gonna fix this on this weekend🙏

**Comment by nator333** [comment]
Changed a way to close an exsisting bubble.
e9a1f43bd782615f167e89b46e377da1e5ae9e04
